name: MiniWorld2
version: '${project.version}'
main: me.radcriminal77.miniworld2.MiniWorld2
api-version: 1.19
load: STARTUP # load is on startup because worlds might use MiniWorld2:empty as their generators for void worlds
authors:
  - TheKDub
  - RadCriminal77
depend:
  - Multiverse-Core
softdepend:
  - WorldGuard
commands:
  CreateVoidWorld:
    description: A helper command to create void worlds
    usage: /<command> world-name
    permission: MiniWorld2.CreateVoidWorld
  Miniature:
    description: Create or delete a miniature world
    usage: /<command> create|remove world-name
permissions:
  MiniWorld2.CreateVoidWorld:
    description: Allows you to use the command /CreateVoidWorld
  MiniWorld2.CreateMiniature:
    description: Allows you to use the command /CreateMiniature
  MiniWorld2.RemoveMiniature:
    description: Allows you tu use the command /RemoveMiniature